// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gtvykicvruylvjdqouyr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd0dnlraWN2cnV5bHZqZHFvdXlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NTY1NTAsImV4cCI6MjA2MTMzMjU1MH0.qu58Jg9orGDsqpn8Gy2IPcEB4r3BFI-qWlZRdUAaJY0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);