// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tyawocaqrhbzkzehezep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5YXdvY2Fxcmhiemt6ZWhlemVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNTkyNDgsImV4cCI6MjA2MDczNTI0OH0.E1e9Ybn89f7PWP6C4z5EjhZ4c1iZg1n0cCUpqTEGoTA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);